// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Organizaciebis_Cnobari.Data;

namespace Organizaciebis_Cnobari.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210701141123_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Organizaciebis_Cnobari.Models.MainAdmin", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("MainAdmin");
                });

            modelBuilder.Entity("Organizaciebis_Cnobari.Models.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Activity")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrganizationPersonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationPersonId");

                    b.ToTable("Organizations");
                });

            modelBuilder.Entity("Organizaciebis_Cnobari.Models.Person", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("BirthDay")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MyPersonOrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalID")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<string>("TelephoneNumbers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MyPersonOrganizationId");

                    b.ToTable("People");
                });

            modelBuilder.Entity("Organizaciebis_Cnobari.Models.PersonOrganization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PersonOrganizations");
                });

            modelBuilder.Entity("Organizaciebis_Cnobari.Models.Organization", b =>
                {
                    b.HasOne("Organizaciebis_Cnobari.Models.PersonOrganization", "OrganizationPerson")
                        .WithMany("MyOrganization")
                        .HasForeignKey("OrganizationPersonId");

                    b.Navigation("OrganizationPerson");
                });

            modelBuilder.Entity("Organizaciebis_Cnobari.Models.Person", b =>
                {
                    b.HasOne("Organizaciebis_Cnobari.Models.PersonOrganization", "MyPersonOrganization")
                        .WithMany("MyPerson")
                        .HasForeignKey("MyPersonOrganizationId");

                    b.Navigation("MyPersonOrganization");
                });

            modelBuilder.Entity("Organizaciebis_Cnobari.Models.PersonOrganization", b =>
                {
                    b.Navigation("MyOrganization");

                    b.Navigation("MyPerson");
                });
#pragma warning restore 612, 618
        }
    }
}
